[package]
name = "xdg-desktop-portal-luminous"
version = "0.3.4"
edition = "2021"

[dependencies]
zbus = { version = "3", default-features = false, features = ["tokio", "url"] }
tokio = { version = "1.28.2", features = ["full"] }
serde = { version = "1.0.71", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = { version = "2.4", features = ["serde"] }
serde_repr = "0.1"
image = { version = "0.24", default-features = false, features = [
	"jpeg",
	"png",
	"pnm",
	"qoi",
] }

slint = "1.1.0"
bitflags = "2.3.3"
enumflags2 = "0.7.7"
once_cell = "1.18.0"
anyhow = "1.0.70"

# pipewire
pipewire = "0.7.2"
libspa-sys = "0.7.2"

libwayshot = { git = "https://github.com/waycrate/wayshot.git" }
rustix = { version = "0.38.8", features = ["fs", "use-libc"] }

# REMOTE
wayland-protocols = { version = "0.30.0", default-features = false, features = [
	"unstable",
	"client",
] }
#wayland-protocols = { version = "=0.30.0-beta.13", features = ["client", "unstable"] }


wayland-protocols-wlr = { version = "0.1.0", default-features = false, features = [
	"client",
] }
wayland-client = { version = "0.30.2" }

wayland-protocols-misc = { version = "0.1.0", features = ["client"] }
xkbcommon = "0.5.0"
tempfile = "3.5.0"
thiserror = "1.0.47"


[build-dependencies]
slint-build = "1.1.0"
