[package]
name = "xdg-desktop-portal-wlrrust"
version = "0.3.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { version = "3", default-features = false, features = ["tokio", "url"] }
tokio = { version = "1.28.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = { version = "2.4", features = ["serde"] }
serde_repr = "0.1"
#toml = "0.7.4"
libwayshot = "0.2.0"
image = { version = "0.24", default-features = false, features = [
	"jpeg",
	"png",
	"pnm",
	"qoi",
] }
#thiserror = "1.0.44"
#anyhow = "1.0.72"
#once_cell = "1.17.1"

slint = "1.1.0"
bitflags = "2.3.3"
enumflags2 = "0.7.7"

[build-dependencies]
slint-build = "1.1.0"
